[features]
seeds = false
skip-lint = false
[programs.localnet]
deposit = "7YKyo13HtdB823RiWHacDR74wc7VeU8vkMZGJDP2nSUB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
